### ISSUE TITLE
install packages failed, error in 0.3.5 (no error in 0.3.2)

### ISSUE THREAD

**Issue by b21986966** [realsirjoe/instagram-scraper#109]
Collecting igramscraper==0.3.5
  Using cached igramscraper-0.3.5.tar.gz (24 kB)

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\<username>\anaconda3\envs\venv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\<username>\\AppData\\Local\\Temp\\pycharm-packaging\\igramscraper\\setup.py'"'"'; __file__='"'"'C:\\Users\\<username>\\AppData\\Local\\Temp\\pycharm-packaging\\igramscraper\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\<username>\AppData\Local\Temp\pycharm-packaging\igramscraper\pip-egg-info'
         cwd: C:\Users\<username>\AppData\Local\Temp\pycharm-packaging\igramscraper\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<username>\AppData\Local\Temp\pycharm-packaging\igramscraper\setup.py", line 8, in <module>
        long_description=Path("README.md").read_text(),
      File "C:\Users\<username>\anaconda3\envs\venv\lib\pathlib.py", line 1217, in read_text
        return f.read()
      File "C:\Users\<username>\anaconda3\envs\venv\lib\encodings\cp1254.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 659: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by erikpic** [comment]
1. Download the project via git clone
2. Remove the line 12 from "README.md"
> Any ⭐️ or contribution is appreciated if you like the project 🤘
3. Run python setup.py install
