### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by lukleu** [realsirjoe/instagram-scraper#115]
it would seem that the setup.py isnt written in an os agnostic way

----- "igramscraper" wird installiert -----
Collecting igramscraper
  Using cached https://files.pythonhosted.org/packages/1c/ef/f86b3ed24902305a0b4d318ecc78b86c168fc4979814fd31ce8dfa6278cc/igramscraper-0.3.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Lukas Leuschen\AppData\Local\Programs\Python\Python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LUKASL~1\\AppData\\Local\\Temp\\pip-install-mf5xm06i\\igramscraper\\setup.py'"'"'; __file__='"'"'C:\\Users\\LUKASL~1\\AppData\\Local\\Temp\\pip-install-mf5xm06i\\igramscraper\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\LUKASL~1\AppData\Local\Temp\pip-install-mf5xm06i\igramscraper\pip-egg-info'
         cwd: C:\Users\LUKASL~1\AppData\Local\Temp\pip-install-mf5xm06i\igramscraper\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LUKASL~1\AppData\Local\Temp\pip-install-mf5xm06i\igramscraper\setup.py", line 8, in <module>
        long_description=Path("README.md").read_text(),
      File "C:\Users\Lukas Leuschen\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1200, in read_text
        return f.read()
      File "C:\Users\Lukas Leuschen\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 659: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
----- Fehler beim Installieren von "igramscraper" -----

**Comment by joonro** [comment]
It seems the special characters in the following line in `README.md` is causing the problem:

    Any ⭐️ or contribution is appreciated if you like the project 🤘
