### ISSUE TITLE
error auth(checkpoint required)

### ISSUE THREAD

**Issue by luthfirrahmanb** [realsirjoe/instagram-scraper#117]
Hi, I've got problem when login to my account, and here's the error message `igramscraper.exception.instagram_auth_exception.InstagramAuthException: Response code is 400. Body: {"message": "checkpoint_required", "checkpoint_url": "/challenge/34888698445/8YlFHGdZLs/", "lock": false, "status": "fail"} Something went wrong. Please report issue., Code:400` . 1 month ago it seems fine, but lately I've got that problem? any idea? thanks :)

**Comment by lukleu** [comment]
+1

**Comment by lukleu** [comment]
any progress on this from anyone?

**Comment by luthfirrahmanb** [comment]
> any progress on this from anyone?

@lukleu I don't know, I'm still waiting for the answer from the developers

**Comment by gitazelle** [comment]
instagram is asking for the code to be sent to the email on file there. (two step verification)

you'll need to run python in interactive mode so that you can type in the code sent to you.
also enable two step verification, use:    instagram.login(True, True)

Don't mess it up too much or it's going to ask for a graphical challenge, which cannot be solved over the console.

**Comment by icearl** [comment]
> instagram is asking for the code to be sent to the email on file there. (two step verification)
> 
> you'll need to run python in interactive mode so that you can type in the code sent to you.
> also enable two step verification, use: instagram.login(True, True)
> 
> Don't mess it up too much or it's going to ask for a graphical challenge, which cannot be solved over the console.

>>> instagram.login(True,True)
 Don't work for me. And  the trackback as follow:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/icearl/anaconda3/lib/python3.7/site-packages/igramscraper/instagram.py", line 1362, in login
    two_step_verificator)
  File "/Users/icearl/anaconda3/lib/python3.7/site-packages/igramscraper/instagram.py", line 1450, in __verify_two_step
    response.status_code)
igramscraper.exception.instagram_auth_exception.InstagramAuthException: Something went wrong when try two step verification. Please report issue., Code:200
