### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by halolokyin** [realsirjoe/instagram-scraper#128]
When I run instagram.like('2368992397079347397'), I got the below error

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\user\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\user\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\user\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\user\AppData\Local\Temp\fz3temp-2\like.py", line 15, in <module>
    instagram.like('1234567890')
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\igramscraper-0.3.5-py3.8.egg\igramscraper\instagram.py", line 1609, in like
    json_response = response.json()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 897, 
in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads        
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode        
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode    
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by SajadAbdr** [comment]
same error

**Comment by anand-sonawane** [comment]
@SajadAbdr and @halolokyin Were you guys able to figure this out?

**Comment by Tomerkat** [comment]
Same error...

**Comment by RubenBenBen** [comment]
any update on this?

**Comment by g-thome** [comment]
i'm getting the same error but using `get_media_by_url()`. interestingly enough, it only happens when my app is running on heroku. i can't reproduce it locally

**Comment by ianho7** [comment]
any solutions in 2022?😂
