### ISSUE TITLE
user_array['entry_data']['ProfilePage'][0]['graphql']['user'] is None

### ISSUE THREAD

**Issue by nleo** [realsirjoe/instagram-scraper#148]
```python
from igramscraper.instagram import Instagram
from time import sleep

instagram = Instagram()

# authentication supported
instagram.with_credentials('xxx', 'xxx', '.')
# instagram.login(two_step_verificator=True)
instagram.login(force=False,two_step_verificator=True)
sleep(2)

username = 'xxx'
followers = []
account = instagram.get_account(username)
sleep(1)
followers = instagram.get_followers(account.identifier, 150, 100, delayed=True) # Get 150 followers of 'kevin', 100 a time with random delay between requests

for follower in followers['accounts']:
  print(follower)
```

```
Message with security code sent to: Email: xxx
Enter security code: 111111
checkpoint required
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    account = instagram.get_account(username)
  File "/usr/local/lib/python3.6/dist-packages/igramscraper/instagram.py", line 1127, in get_account
    if user_array['entry_data']['ProfilePage'][0]['graphql']['user'] is None:
KeyError: 'graphql'
```

**Comment by nleo** [comment]
I use another package with integration with firefox https://instaloader.github.io/troubleshooting.html#login-error
