### ISSUE TITLE
using cookie

### ISSUE THREAD

**Issue by shahreahang** [realsirjoe/instagram-scraper#149]
Hello,

I want to use saved cookie to get information from instagram, I used this code :

```
from context import Instagram # pylint: disable=no-name-in-module
from time import sleep
# If account is public you can query Instagram without auth
instagram = Instagram()

cookie="./sessions/yyyy.txt"
instagram.set_cookies(cookie)
```
But I got this error :

```
C:\instascraper>py insta.py
Traceback (most recent call last):
  File "C:\instascraper\insta.py", line 12, in <module>
    instagram.set_cookies(cookie)
  File "C:\instascraper\igramscraper\instagram.py", line 55, in set_cookies
    cj.load()
  File "C:\Python39\lib\http\cookiejar.py", line 1799, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "C:\Python39\lib\http\cookiejar.py", line 2020, in _really_load
    raise LoadError(
http.cookiejar.LoadError: './sessions/yyyy.txt' does not look like a Netscape format cookies file
```

what is the problem ?
This cookie created by login method and the patch is currect.
I use windows 10 and python 3.9

**Comment by automatata** [comment]
Encounter the same error. I'm new to this lib but I used
https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid
to export my cookies and it worked for me.
