### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by GhostXu11** [realsirjoe/instagram-scraper#158]
Today when I tried to log in, it keeps pop **Something went wrong. Please report issue., Code:429**, I also changed proxies and accounts, still not working. So i want to know if this is the problem of this scraper?

**Comment by smdmts** [comment]
I got a same issue, any changes in Instagram?

**Comment by GhostXu11** [comment]
> I got a same issue, any changes in Instagram?

Yes, it seems that Instagram changed something in the part of authentication.

**Comment by instasck** [comment]
seems it will not let login without JS

**Comment by instasck** [comment]
<html lang="en" class="no-js not-logged-in ">

**Comment by instasck** [comment]
Any solutions ?

**Comment by goody44** [comment]
It looks like insta has blocked the default user agent for the requests lib e.g. requests to instagram.com with the user agent 'python-requests/2.23.0' results in a 429 response.
I changed the default user agent for a couple of requests and it works for me now.
Here are the changes I made - https://github.com/goody44/instagram-scraper/commit/5b2a00163a6d4be71415923c1366bfc0a0437a3c

**Comment by instasck** [comment]
> It looks like insta has blocked the default user agent for the requests lib e.g. requests to instagram.com with the user agent 'python-requests/2.23.0' results in a 429 response.
> I changed the default user agent for a couple of requests and it works for me now.
> Here are the changes I made - [goody44@5b2a001](https://github.com/goody44/instagram-scraper/commit/5b2a00163a6d4be71415923c1366bfc0a0437a3c)

Well I never used "python headers", so generated headers show:
Mozilla/5.0 (Linux; Android 7.0; Lenovo K33b36 Build/NRD90N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.109 Mobile Safari/537.36 Instagram 41.0.0.13.92 Android (24/7.0; 480dpi; 1080x1920; LENOVO/Lenovo; Lenovo K33b36; K33b36; qcom; pt_BR; 103516666)

I don't "login" as user, I scrape on public data, and it still not let me scrap.

**Comment by victorDaniloCasta** [comment]
Where can I change the user agent?

**Comment by orenmm** [comment]
> It looks like insta has blocked the default user agent for the requests lib e.g. requests to instagram.com with the user agent 'python-requests/2.23.0' results in a 429 response.
> I changed the default user agent for a couple of requests and it works for me now.
> Here are the changes I made - [goody44@5b2a001](https://github.com/goody44/instagram-scraper/commit/5b2a00163a6d4be71415923c1366bfc0a0437a3c)

can you help me please? I am using https://github.com/teja156/instagram-unfollow-checker , that uses instagram-scraper, how do I update the agent on it?

**Comment by godpowerscn** [comment]
it not works now?

**Comment by dschep** [comment]
@goody44, does your fork still work for you? I got pass the 429 error using your fork, but now get this error:

```
Traceback (most recent call last):
  File "top9.py", line 98, in <module>
    top9()
  File "/home/dschep/top9/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dschep/top9/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dschep/top9/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dschep/top9/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "top9.py", line 43, in top9
    instagram.login(two_step_verificator=tfa)
  File "/home/dschep/top9/venv/lib/python3.7/site-packages/igramscraper/instagram.py", line 1369, in login
    response.status_code)
igramscraper.exception.instagram_auth_exception.InstagramAuthException: Response code is 400. Body: {"message": "checkpoint_required", "checkpoint_url": "/challenge/364941233/XvJ0mhKfM1/", "lock": false, "flow_render_type": 0, "status": "fail"} Something went wrong. Please report issue., Code:400
```

**Comment by instasck** [comment]
You got blocked and on "challenge" page.
Don't use user to scrape

**Comment by dschep** [comment]
Hah... @instasck, in the context of this thread, that's not very useful input. But In my personal case, it actually is. I didn't need to log in for my use case 🤦

**Comment by instasck** [comment]
> Hah... @instasck, in the context of this thread, that's not very useful input. But In my personal case, it actually is. I didn't need to log in for my use case 🤦

I know they block IP based.
Just rotate your 4g IP every few minutes.
