### ISSUE TITLE
Rotating proxies don't work with large requests

### ISSUE THREAD

**Issue by snapmademedoit** [realsirjoe/instagram-scraper#197]
Traceback (most recent call last):
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?query_hash=c76146de99bb02f6415203be841dd25a&variables=%7B%22id%22%3A%221523221554%22%2C%22first%22%3A%22100000%22%2C%22after%22%3A%22QVFBOGhyRjRfbXVPTVZxMEFheEduZUhJMjFaYksyRXVqbWZtbnNrS1BSeXhPY2plUTkwVm1Ec3J6VXlURWFWQXVOV1I5MkNlZm03azFBTHJMMGdicjNMaw%3D%3D%22%7D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xx\Desktop\instagram-snap\test1.py", line 30, in <module>
    followers = instagram.get_followers(account.identifier, 100000, 50, delayed=True)  # Get 10 followers of 'kevin', 100 a time with random delay between requests
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\igramscraper-0.3.5-py3.9.egg\igramscraper\instagram.py", line 929, in get_followers
    response = self.__req.get(
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\as\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query/?query_hash=c76146de99bb02f6415203be841dd25a&variables=%7B%22id%22%3A%221523221554%22%2C%22first%22%3A%22100000%22%2C%22after%22%3A%22QVFBOGhyRjRfbXVPTVZxMEFheEduZUhJMjFaYksyRXVqbWZtbnNrS1BSeXhPY2plUTkwVm1Ec3J6VXlURWFWQXVOV1I5MkNlZm03azFBTHJMMGdicjNMaw%3D%3D%22%7D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

As soon as my proxy rotates this error is caused. Is there a way have it retry slower so proxy can take time to rotate?

**Comment by snapmademedoit** [comment]
I did some really dirty stuff to instagram.py to solve my issue. To anyone reading this having a similar problem, this is an awful solution please don't implement it in anything that's production

I replaced

` response = self.__req.get(
                        endpoints.get_followers_json_link(variables),
                        headers=headers)`

WIth this

`for t in range(10):
                try:
                    response = self.__req.get(
                        endpoints.get_followers_json_link(variables),
                        headers=headers)
                    break
                except:
                    time.sleep(2)`

All in all a disgusting patch nobody should ever do, but it seems to be getting the job done.

**Comment by instasck** [comment]
I get it too for rotate. need to retry ....
How ofen do you rotate ? I found it less effective lately.
