### ISSUE TITLE
Error text with 200 responce

### ISSUE THREAD

**Issue by instasck** [realsirjoe/instagram-scraper#212]
anything to do with this responce ?
````
  File "C:\Users\manager\Dropbox\instagramAutomation\real\info_grabber\instagramscraper\igramscraper\instagram.py", line 1322, in get_account
    return user_array['entry_data']['ProfilePage'][0]['graphql']['user']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manager\Dropbox\instagramAutomation\real\info_grabber\follow_grabber_online.py", line 278, in worker
    data = instagram_scrapper.get_account(username, _json=True)
  File "C:\Users\manager\Dropbox\instagramAutomation\real\info_grabber\instagramscraper\igramscraper\instagram.py", line 1329, in get_account
    raise InstagramException.default(response.text,
instagramscraper.igramscraper.exception.instagram_exception.InstagramException: Response code is 200. Body: <!DOCTYPE html><html class="_9dls touch" lang="pt-br" dir="ltr"><head><link data-default-icon="https://static.cdninstagram.com/rsrc.php/v3/y9/r/uhXzVt-dlj4.png" rel="icon" sizes="192x192" href="https://static.cdninstagram.com/rsrc.php/v3/y9/r/uhXzVt-dlj4.png" /><meta name="robots" content="noarchive, noimageindex" /><meta charset="utf-8" /><meta name="apple-mobile-web-app-status-bar-style" content="default" /><meta name="mobile-web-app-capable" content="yes" /><meta name="theme-color" content="#ffffff" /><meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" /><link rel="apple-touch-icon" sizes="76x76" href="https://static.cdninstagram.com/rsrc.php/v3/y-/r/99-GUnvE0f7.png" /><link rel="apple-touch-icon" sizes="120x120" href="https://static.cdninstagram.com/rsrc.php/v3/y0/r/1RQf-TYXzi3.png" /><link rel="apple-touch-icon" sizes="152x152" href="https://static.cdninstagram.com/rsrc.php/v3/yP/r/eqX21-nJRJz.png" /><link rel="apple-touch-icon" sizes="167x167" href="https://static.cdninstagram.com/rsrc.php/v3/y9/r/5zNbpyWm4sA.png" /><link rel="apple-touch-icon" sizes="180x180" href="https://static.cdninstagram.com/rsrc.php/v3/yb/r/rE5FKFpjQu_.png" /><link data-default-icon="https://static.cdninstagram.com/rsrc.php/yS/r/f_5NUHW7AZC.ico" rel="shortcut icon" type="image/x-icon" href="https://static.cdninstagram.com/rsrc.php/yS/r/f_5NUHW7AZC.ico" /><link rel="alternate" href="https://www.instagram.com/nashiraarno/" hreflang="x-default" /><link rel="alternate" href="https://www.instagram.com/nashiraarno/?hl=en" hreflang="en" /><link rel="alternate" href="https://www.instagram.com/nashiraarno/?hl=fr" hreflang="fr" /><link rel="alternate" href="https://www.instagram.com/nashiraarno/?hl=it" hreflang="it" /><link rel="alternate" 

...


 Something went wrong. Please report issue., Code:200
````
full log:

[log.txt](https://github.com/realsirjoe/instagram-scraper/files/8811630/log.txt)

**Comment by instasck** [comment]
I dont think it is a blocking issue just a page need to be redirected

**Comment by samamou** [comment]
Same!
`Traceback (most recent call last):
  File "/main.py", line 15, in <module>
    account = instagram.get_account_by_id(3)
  File "/venv/lib/python3.8/site-packages/igramscraper/instagram.py", line 109, in get_account_by_id
    return self.get_account(username)
  File "/venv/lib/python3.8/site-packages/igramscraper/instagram.py", line 1127, in get_account
    if user_array['entry_data']['ProfilePage'][0]['graphql']['user'] is None:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by instasck** [comment]
Not sure it total fix that dont break other
Line 167 change to:
```
            headers = {
                'cookie': cookies,
                'referer': endpoints.BASE_URL + '/',
                'x-csrftoken': csrf,
                'X-ASBD-ID': '198387',
                'X-IG-App-ID': '936619743392459'
            }
```

add this (for logged in scrapers):
```
    def get_account_logged_in(self, username, _json=False, timeout=None):
        response = self.__req.get(endpoints.get_account_page_link_logged_in(
            username), headers=self.generate_headers(self.user_session), timeout=timeout)

        user_data = json.loads(response.text)
        if user_data['status'] == 'fail':
            return None
        elif user_data['status'] == 'ok':
            user = user_data['data']['user']
            if _json:
                return user
            else:
                return Account(user)

    def get_account(self, username, _json=False, timeout=None):
        """
        :param timeout:
        :param username: username
        :param _json: should it return in Account or in json?
        :return: Account
        """
        if self.user_session:
            return self.get_account_logged_in(username, _json=_json, timeout=timeout)

```

**Comment by gabett** [comment]
@instasck got any update concerning the fix of this bug? I am experiencing the same issue as well.
