### ISSUE TITLE
400 checkpoint required

### ISSUE THREAD

**Issue by artplan1** [realsirjoe/instagram-scraper#24]
Hey, any plans to implement checkpoint_required pass?

this is what I see when I try to login every time
```
igramscraper.exception.instagram_auth_exception.InstagramAuthException: Response code is 400. Body: {"message": "checkpoint_required", "checkpoint_url": "/challenge/274057674/xDXvMbHaOG/", "lock": false, "status": "fail"} Something went wrong. Please report issue., Code:400
```

and it didn't go away even if I accept it in the app

**Comment by realsirjoe** [comment]
This means that instagram wants to verify your account either by phone or email, we provide a simple cli interface for such instances.
just use login() function with two_step_verificator=True as argument that should do the trick!

tell me if this resolved your issue

**Comment by artplan1** [comment]
thank you @realsirjoe 
this is stacktrace after I tried it:

```python
Select where to send security code
Email: ****** - 1
Phone: *** ***-** - 0
Your choice: 1
Enter security code: 698270
checkpoint required
Traceback (most recent call last):
  File "my.py", line 6, in <module>
    instagram.login(two_step_verificator=True)
  File "/Users/artem/projects/instagram-scraper/igramscraper/instagram.py", line 1301, in login
    if not response.json()['authenticated']:
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by amansingh9097** [comment]
anyone actually looking into this? I'm facing this issue too...

```Select where to send security code
Email: ******* - 1
Phone: ******** - 0
Your choice: 0
Enter security code: 062571
checkpoint required
Traceback (most recent call last):
  File "D:/personal-repo/insta-influencer/insta_ranker.py", line 8, in <module>
    instagram.login(two_step_verificator=True)
  File "D:\personal-repo\insta-influencer\igramscraper\instagram.py", line 1301, in login
    if not response.json()['authenticated']:
  File "D:\personal-repo\insta-influencer\influ-venv\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

Process finished with exit code 1```

**Comment by YUxiangLuo** [comment]
> thank you @realsirjoe
> this is stacktrace after I tried it:
> 
> ```python
> Select where to send security code
> Email: ****** - 1
> Phone: *** ***-** - 0
> Your choice: 1
> Enter security code: 698270
> checkpoint required
> Traceback (most recent call last):
>   File "my.py", line 6, in <module>
>     instagram.login(two_step_verificator=True)
>   File "/Users/artem/projects/instagram-scraper/igramscraper/instagram.py", line 1301, in login
>     if not response.json()['authenticated']:
>   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> response status there at `instagram-scraper/igramscraper/instagram.py", line 1301` is 200
> response type is html (root page I guess)

same error, is there any solution?

**Comment by mnikoli** [comment]
Hi I have a similar issue, namely when I was obtaining followers from a user with a high number of followers (aroung 400k) I first received a 502 error. After rerunning the script I got this error:
traceback (most recent call last):
  File "get_account_followers_original.py", line 6, in <module>
    instagram.login(force=False,two_step_verificator=True)
  File "/Users/milos/miniconda3/igram/igramscraper/instagram.py", line 1319, in login
    and response.json()['message'] == 'checkpoint_required'
  File "/Users/milos/miniconda3/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/milos/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/milos/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/milos/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any clue what might be the issue?
Thanks in advance.
Milos

**Comment by Lainur** [comment]
Same issue. Tried this(https://instazood.com/blog/how-to-fix-checkpoint-required-error-on-instagram/), but no effect..

**Comment by sbr2567** [comment]
Same issue as mnikoli. Any solutions?

**Comment by sam021313** [comment]
@realsirjoe are there any workarounds at the moment?

**Comment by simoncrowe** [comment]
I'm experiencing a similar problem when attempting to call `login` with `two_step_verificator=True`:

```
  File "/home/sc/git/instagraph-bot/ig_bot/scraping.py", line 21, in get_authenticated_igramscraper
    client.login(two_step_verificator=True)
  File "/home/sc/.virtualenvs/instagraph-bot/src/igramscraper/igramscraper/instagram.py", line 1361, in login
    response = self.__verify_two_step(response, cookies,
  File "/home/sc/.virtualenvs/instagraph-bot/src/igramscraper/igramscraper/instagram.py", line 1447, in __verify_two_step
    raise InstagramAuthException(
igramscraper.exception.instagram_auth_exception.InstagramAuthException: Something went wrong when try two step verification. Please report issue., Code:200
```

**Comment by ttc9082** [comment]
> I'm experiencing a similar problem when attempting to call `login` with `two_step_verificator=True`:
> 
> ```
>   File "/home/sc/git/instagraph-bot/ig_bot/scraping.py", line 21, in get_authenticated_igramscraper
>     client.login(two_step_verificator=True)
>   File "/home/sc/.virtualenvs/instagraph-bot/src/igramscraper/igramscraper/instagram.py", line 1361, in login
>     response = self.__verify_two_step(response, cookies,
>   File "/home/sc/.virtualenvs/instagraph-bot/src/igramscraper/igramscraper/instagram.py", line 1447, in __verify_two_step
>     raise InstagramAuthException(
> igramscraper.exception.instagram_auth_exception.InstagramAuthException: Something went wrong when try two step verification. Please report issue., Code:200
> ```

same

**Comment by EddyDavies** [comment]
I was able to fix this logging into the account I am using to scrap on instagram.com and in settings, profile activity, clicking "it was me" for a bunch of the login attempts.
