### ISSUE TITLE
instgram.like function gives an error

### ISSUE THREAD

**Issue by kk3nny** [realsirjoe/instagram-scraper#50]
I'm getting this error when I'm trying to use the like function. All else is working fine.
I'm using Windows 10, Python 3.6.8.

This is the error that I get :

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    instagram.like('2148060002479529337')
  File "C:\Python36\lib\site-packages\igramscraper\instagram.py", line 1510, in like
    json_response = response.json()
  File "C:\Python36\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by kk3nny** [comment]
The media I was trying to like did not exist! Sorry to bother
