### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by umangraval** [realsirjoe/instagram-scraper#89]
this error came up today, yesterday it was working fine. I don't why it showed up. I faced this issue in other python packages too.
```
Traceback (most recent call last):
  File "autocomment.py", line 18, in <module>
    comment = instagram.add_comment(m.identifier, 'Follow @covid.ai for the latest coronavirus stats')
  File "/home/covid19/api_management/flaskapp/env/lib/python3.6/site-packages/igramscraper/instagram.py", line 1455, in add_comment
    json_response = response.json()
  File "/home/covid19/api_management/flaskapp/env/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by lukleu** [comment]
did you ever solve this? @umangraval

**Comment by K1on4ik** [comment]
There was no problem before, but today it appeared. Has anyone solved the authorization problem?

**Comment by umangraval** [comment]
@lukleu it started working fine the other day.
