### ISSUE TITLE
get_paginate_medias error 500 (on latest version)

### ISSUE THREAD

**Issue by avifatal** [realsirjoe/instagram-scraper#97]
Hi,
this is how I install the scraper: 
`pip install git+git://github.com/realsirjoe/instagram-scraper.git`
which means - latest version.

I think have the same problem as here: https://github.com/realsirjoe/instagram-scraper/issues/45
```
igramscraper.exception.instagram_exception.InstagramException: Response code is 400. Body: {"message": "execution failure", "errors": [{"message": "execution error", "locations": []}], "data": {"user": null}, "status": "fail"} Something went wrong. Please report issue., Code:400
```
BTW, `get_media` is working fine...

Thanks

**Comment by realsirjoe** [comment]
Please install it via pip install igramscraper

**Comment by avifatal** [comment]
@realsirjoe  thank you. I will try that.

 Can you please explain why the session is deleted right after it is been created?
https://github.com/realsirjoe/instagram-scraper/blob/048ecefcd90dc9addcdeb9dee71ecaefb6778a1d/igramscraper/instagram.py#L73

Thanks

**Comment by avifatal** [comment]
The installation via `pip install igramscraper` creates a different error.
this is why  run `pip install git+git://github.com/realsirjoe/instagram-scraper.git`

The error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/services/main.py", line 26, in get_following
    followers.get_following(avatar,request.args.get('username'), request.args.get('take', type=int), request.args.get('skip', type=int) ,request.args.get('next_page')
  File "/app/services/lib/followers.py", line 8, in get_following
    return get('get_following',avatar,username, take, skip, next_page)
  File "/app/services/lib/followers.py", line 20, in get
    following = method_to_call(account.identifier, take, skip, delayed=True, end_cursor=next_page)
  File "/usr/local/lib/python3.8/site-packages/igramscraper/instagram.py", line 989, in get_following
    data['next_page'] = next_page
UnboundLocalError: local variable 'data' referenced before assignment
````
