### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by kingkimohero69** [realsirjoe/instagram-scraper#99]
Hi, 
Why do i get this error 
```Traceback (most recent call last):
  File "get-followers-il7e9.py", line 14, in <module>
    followers = instagram.get_followers(account.identifier, 3000000, 100, delayed=True) # Get 150 followers of 'kevin', 100 a time with random delay between requests
  File "/var/instagram-scraper/igramscraper/instagram.py", line 859, in get_followers
    headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by kingkimohero69** [comment]
solved by using https in proxy not only http
